### ISSUE TITLE
A question about the generated data

### ISSUE THREAD

**Issue by zxz0928** [timoschick/dino#10]
Thanks for your great job.
I want to get some semantic similar pairs use your method,I use the code
{
  "task_name": "sts",
  "labels": {
    "1": {
      "instruction": "Task: Write two sentences that mean the same thing.\nSentence 1: \"<X1>\"\nSentence 2: \"",
      "counter_labels": []
    }
  }
}

but my result is as follows:
{"text_a": "a man with a hard hat is dancing", "text_b": "a man with a hard hat is dancing", "label": "1"}
{"text_a": "a man with a hard hat is dancing", "text_b": "A man with a hard hat is dancing", "label": "1"}
{"text_a": "a young child is riding a horse", "text_b": "a child is riding a horse", "label": "1"}
{"text_a": "a young child is riding a horse", "text_b": "A child is riding a horse", "label": "1"}
{"text_a": "a man is feeding a mouse to a snake", "text_b": "a man is feeding a mouse to a snake.", "label": "1"}
{"text_a": "a man is feeding a mouse to a snake", "text_b": "A man is feeding a mouse to a snake", "label": "1"}
{"text_a": "a woman is playing the guitar", "text_b": "a woman is playing the guitar", "label": "1"}
{"text_a": "a woman is playing the guitar", "text_b": "the man is playing the guitar", "label": "1"}
{"text_a": "a woman is playing the flute", "text_b": "a woman is playing the flute", "label": "1"}
{"text_a": "a woman is playing the flute", "text_b": "a woman is playing the flute", "label": "1"}
{"text_a": "a woman is cutting an onion", "text_b": "an onion is cutting a woman", "label": "1"}
{"text_a": "a woman is cutting an onion", "text_b": "an onion is cutting a woman", "label": "1"}
{"text_a": "a man is erasing a chalk board", "text_b": "a man is erasing a chalkboard.", "label": "1"}
{"text_a": "a man is erasing a chalk board", "text_b": "a man is erasing a chalk board.", "label": "1"}
{"text_a": "a woman is carrying a boy", "text_b": "a boy is carrying a woman", "label": "1"}
{"text_a": "a woman is carrying a boy", "text_b": "A woman is carrying a boy", "label": "1"}
{"text_a": "three men are playing guitars", "text_b": "Three men are playing guitars", "label": "1"}
{"text_a": "three men are playing guitars", "text_b": "three guitarists are playing guitars", "label": "1"}
{"text_a": "a woman peels a potato", "text_b": "a woman peels a potato", "label": "1"}
{"text_a": "a woman peels a potato", "text_b": "a woman peels a potato", "label": "1"}
most of the generated data are as same as the original one ,or only change the char "a" to "A",I think these data are meaningless，did I do something wrong?

**Comment by timoschick** [comment]
Hi @zxz0928, you didn't necessarily do something wrong. Indeed, writing two sentences that mean the exact same thing is what models have most difficulty with (as opposed to writing things that are somewhat similar or on completely different topics) - we have some more discussion of this in [the final version of the paper](https://arxiv.org/abs/2104.07540). What we did for our experiments was to filter out examples where `text_a == text_b` (as those provide no signal to a biencoder architecture anyway). 

You can also look at [some of our publicly available datasets](https://github.com/timoschick/dino#-generated-dinos) to compare the quality of sentences pairs in those datasets with the ones you've created.

**Comment by zxz0928** [comment]
Thank you very much for your answer.It really helps a lot.
