### ISSUE TITLE
questions about generation.py

### ISSUE THREAD

**Issue by SumilerGAO** [timoschick/dino#12]
Hi, 

Thanks for your impressive work and for sharing the codes! 

When I implement your codes, I can't find the definitions for  "_init_sequence_length_for_generation". Did I miss something?

Thanks!

Best regards,
Sumiler

Updates:

Sorry. I think it is due to the different versions of "transformers." I have fixed it. Thanks!

Best,

**Comment by SumilerGAO** [comment]
Sorry. I think it is due to the different versions of  "transformer."  I have fixed it. Thanks!

**Comment by jasony123123** [comment]
How did you fix this? What version of "transformers" did you install?
