### ISSUE TITLE
Why using a single instruction as input?

### ISSUE THREAD

**Issue by jiacheng-ye** [timoschick/dino#13]
Hi Dr. Timo, thanks for your amazing work and code! I'm wondering why do you use a single instruction as input in a batch? I notice that when I generating x2, I have to set the batch size to 2, which is relatively small and results in a poor inference efficiency. What's the intuition behind this design?

**Comment by timoschick** [comment]
Hi @jiacheng-ye, I'm not sure exactly what you mean by "using a single instruction as input" - could you elaborate on that? For generating *x*<sub>1</sub>, you can scale up the batch size for maximum inference efficiency (i.e., full GPU usage). For *x*<sub>2</sub>, you cannot specify a batch size but instead control the number of entries to generate per input (*x*<sub>1</sub>) and label using `--num_entries_per_input_and_label `.
